refs_index_file: /lustre/scratch103/pathogen/pathpipe/refs/refs.index
default_data_hierarchy: genus:species-subspecies:TRACKING:projectssid:sample:technology:library:lane

eukaryotes:
  base_directory: /lustre/scratch103/pathogen/pathpipe/eukaryotes/seq-pipelines
  output_json_file: /lustre/scratch103/pathogen/pathpipe/eukaryotes/alignments.json

helminths:
  base_directory: /lustre/scratch103/pathogen/pathpipe/helminths/seq-pipelines
  output_json_file: /lustre/scratch103/pathogen/pathpipe/helminths/alignments.json

metahit:
  base_directory: /lustre/scratch103/pathogen/pathpipe/metahit/seq-pipelines
  output_json_file: /lustre/scratch103/pathogen/pathpipe/metahit/alignments.json

prokaryotes:
  base_directory: /lustre/scratch103/pathogen/pathpipe/prokaryotes/seq-pipelines
  output_json_file: /lustre/scratch103/pathogen/pathpipe/prokaryotes/alignments.json

viruses:
  base_directory: /lustre/scratch103/pathogen/pathpipe/viruses/seq-pipelines
  output_json_file: /lustre/scratch103/pathogen/pathpipe/viruses/alignments.json
